export const data = [
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    '   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem veritatis sint itaque quod saepe suscipit eligendi corrupti voluptatum necessitatibus mollitia ex, molestias autem veniam perferendis aspernatur eum soluta ducimus? Vitae dolorem, molestias minus nulla libero omnis. Non quaerat eveniet voluptates.',
    
]